barang/urls.py
from django.urls import path
from .views import *
app_name = 'barang'
urlpatterns = [
    path('daftar_barang', display_barang, name='daftar_barang'),
	path('detail_barang/<str:id>', detail_barang, name='detail_barang'),
	path('delete_barang/<str:id>', delete_barang, name='delete_barang'),
    path('update_barang/<str:id>', update_barang, name='update_barang'),
    path('create_barang', create_barang, name='create_barang'),
]

chat/urls.py
from django.urls import path
from .views import *
app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
    path('list-admin', list_chat_admin, name='list-chat')
]

pesanan/urls.py
from django.urls import path
from .views import *

app_name = 'pesanan'
urlpatterns = [
    path('', pesanan_anggota, name='pesanan_anggota'),
    path('pesanan_admin', pesanan_admin, name='pesanan_admin'),
    path('update_pesanan', update_pesanan, name='update_pesanan'),
    path('daftar_pesanan', daftar_pesanan_anggota,
         name='daftar_pesanan_anggota'),
    path('daftar_pesanan_admin', daftar_pesanan_admin,
         name='daftar_pesanan_admin'),
]

toys_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import level.urls
import pesanan.urls
import item.urls
import pengiriman.urls
import barang.urls
import chat.urls
import login.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', include(main.urls)),
    path('barang/', include(barang.urls)),
    path('level/', include(level.urls)),
    path('pesanan/', include(pesanan.urls)),
    path('item/', include(item.urls)),
    path('pengiriman/', include(pengiriman.urls)),
    path('chat/', include(chat.urls)),
    path('login/', include(login.urls))
]

barang/models.py
from django.db import models

# Create your models here.

barang/forms.py
from django import forms

from toysrent_db.models import Item, Anggota

class FormInfoBarangLevel(forms.Form):
    porsi_royalti = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'id': 'porsi_royalti',
                'class': 'form-control',
                'placeholder': 'Royalti'
            }
        )
    )

    harga_sewa = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'id': 'harga_sewa',
                'class': 'form-control',
                'placeholder': 'Harga sewa'
            }
        ),
    )

class FormBarang(forms.Form):
    id_barang = forms.CharField(
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'id': 'id_barang',
                'class': 'form-control',
                'placeholder': 'ID Barang'
            }
        ),
        label='ID Barang'
    )

    nama_item = forms.ModelChoiceField(
        queryset=Item.objects.all(),
        widget=forms.Select(
            attrs={
                'id': 'nama_item',
                'class': 'form-control',
                'placeholder': 'Nama Item'
            }
        ),
        label='Nama Item',
        empty_label='Pilih nama item'
    )

    warna = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'id': 'warna',
                'class': 'form-control',
                'placeholder': 'Warna'
            },
        ),
        label='Warna',
        required=False
    )

    url_foto = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'id': 'url_foto',
                'class': 'form-control',
                'placeholder': 'URL Foto',
                'rows': '1'
            }
        ),
        label='URL',
        required=False
    )

    kondisi = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'id': 'kondisi',
                'class': 'form-control',
                'placeholder': 'Kondisi',
                'rows': '1'
            }
        ),
        label='Kondisi'
    )

    lama_penggunaan = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'id': 'lama_penggunaan',
                'class': 'form-control',
                'placeholder': 'Lama penggunaan dalam bulan'
            }
        ),
        label='Lama Penggunaan',
        required=False
    )

    no_ktp_penyewa = forms.ModelChoiceField(
        queryset=Anggota.objects.all(),
        widget=forms.Select(
            attrs={
                'id': 'no_ktp_penyewa',
                'class': 'form-control',
                'placeholder': 'Nama Pemilik'
            }
        ),
        label='Nama Pemilik',
        empty_label='Pilih nama pemilik barang'
    )

barang/views.py
from django.db import connection
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from toysrent_db.models import *
from .forms import FormBarang, FormInfoBarangLevel

page_size = 10
# Create your views here
def update_barang(request, id):
    if request.session['role'] != 'admin':
        return HttpResponseRedirect(reverse('barang:daftar_barang'))
    barang = Barang.objects.raw('SELECT * FROM BARANG WHERE id_barang = %s', [id])
    info = InfoBarangLevel.objects.raw('SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s', [id])
    levels = LevelKeanggotaan.objects.raw('SELECT * FROM LEVEL_KEANGGOTAAN')
    formset = formset_factory(FormInfoBarangLevel, extra=len(levels), max_num=len(levels))
    initial_barang = {
        'id_barang': barang[0].id_barang,
        'nama_item': barang[0].nama_item.nama,
        'warna': barang[0].warna,
        'url_foto': barang[0].url_foto,
        'kondisi': barang[0].kondisi,
        'lama_penggunaan': barang[0].lama_penggunaan,
        'no_ktp_penyewa': barang[0].no_ktp_penyewa.no_ktp.no_ktp
    }
    level = []
    initial_info = []
    for l in levels:
        exists = False
        for i in info:
            if l == i.nama_level:
                level.append(i.nama_level)
                initial_info.append({
                    'harga_sewa': i.harga_sewa,
                    'porsi_royalti': i.porsi_royalti
                })
                exists = True
                break
        if not exists:
            level.append(l)
            initial_info.append({
                'harga_sewa': '',
                'porsi_royalti': ''
            })

    if request.method == 'POST':
        form_barang = FormBarang(request.POST, prefix="barang", initial=initial_barang)
        form_info = formset(request.POST, prefix="info", initial=initial_info)
        if form_barang.is_valid() and form_info.is_valid():
            id_barang = initial_barang['id_barang']
            if form_barang.has_changed():
                for field in form_barang.changed_data:
                    if field != 'id_barang':
                        id_barang = form_barang.cleaned_data.get('id_barang')
                    data = [form_barang.cleaned_data.get(field), form_barang.cleaned_data.get('id_barang')]
                    with connection.cursor() as cursor:
                        cursor.execute(
                            'UPDATE barang SET %s = %s WHERE id_barang = %s' % (field, '%s', '%s'), data
                        )
            index = 0
            for form in form_info:
                harga_sewa = form.cleaned_data.get('harga_sewa')
                porsi_royalti = form.cleaned_data.get('porsi_royalti')
                with connection.cursor() as cursor:
                    cursor.execute(
                        'INSERT INTO INFO_BARANG_LEVEL VALUES (%s, %s, %s, %s) ON CONFLICT (id_barang, nama_level) DO UPDATE SET harga_sewa=%s, porsi_royalti=%s',
                        [id_barang, level[index].nama_level, harga_sewa, porsi_royalti, harga_sewa, porsi_royalti]
                    )
                    index += 1
            return HttpResponseRedirect(reverse('barang:daftar_barang'))
    form_barang = FormBarang(initial=initial_barang, prefix="barang")
    form_info = formset(prefix="info", initial=initial_info)
    level.reverse()
    return render(request, 'create_barang.html', {
        'barang': form_barang,
        'info': form_info,
        'level': level,
        'judul': 'Update'
    })


def save(barang, info_level, level):
    id_barang = barang.cleaned_data.get('id_barang')
    nama_item = barang.cleaned_data.get('nama_item').nama
    warna = barang.cleaned_data.get('warna')
    url_foto = barang.cleaned_data.get('url_foto')
    kondisi = barang.cleaned_data.get('kondisi')
    lama_penggunaan = barang.cleaned_data.get('lama_penggunaan')
    no_ktp_penyewa = barang.cleaned_data.get('no_ktp_penyewa').no_ktp.no_ktp
    data_barang = [id_barang, nama_item, warna, url_foto, kondisi, lama_penggunaan, no_ktp_penyewa]

    with connection.cursor() as cursor:
        cursor.execute('INSERT INTO BARANG VALUES (%s, %s, %s, %s, %s, %s, %s)', data_barang)
        index = 0
        for info in info_level.forms:
            nama_level = level[index]
            harga_sewa = info.cleaned_data.get('harga_sewa')
            porsi_royalti = info.cleaned_data.get('porsi_royalti')
            cursor.execute('INSERT INTO INFO_BARANG_LEVEL VALUES (%s, %s, %s, %s)',
                           [id_barang, nama_level, harga_sewa, porsi_royalti])
            index += 1


def create_barang(request):
    if request.session['role'] != 'admin':
        return HttpResponseRedirect(reverse('barang:daftar_barang'))
    level_raw = LevelKeanggotaan.objects.raw('SELECT * FROM LEVEL_KEANGGOTAAN')
    level = [level.nama_level for level in level_raw]
    form_info = formset_factory(FormInfoBarangLevel, extra=len(level))
    if request.method == 'POST':
        form_barang = FormBarang(request.POST)
        form_info = form_info(request.POST, prefix='level')
        if form_info.is_valid() and form_barang.is_valid():
            save(form_barang, form_info, level)
            return HttpResponseRedirect(reverse('barang:daftar_barang'))
        else:
            return HttpResponseRedirect(reverse('barang:create_barang'))
    form_info = form_info(prefix='level')
    form_barang = FormBarang()
    level.reverse()
    return render(request, 'create_barang.html', {
        'barang': form_barang,
        'info': form_info,
        'level': level,
        'judul': 'Penambahan'
    })


def perform_delete(id):
    with connection.cursor() as cursor:
        cursor.execute(
            'DELETE FROM barang where id_barang = %s', [id]
        )


def delete_barang(request, id):
    if request.session['role'] != 'admin':
        return HttpResponseRedirect(reverse('barang:daftar_barang'))
    perform_delete(id)
    return HttpResponseRedirect(reverse('barang:daftar_barang'))


def display_barang(request):
    sort_method = 'id_barang' if request.GET.get('sort', 'id_barang') == '' else request.GET.get('sort', 'id_barang')
    filter_method = None if request.GET.get('filter', None) == '' else request.GET.get('filter', None)
    kategori = list(Kategori.objects.raw('SELECT * FROM KATEGORI'))
    page_number = int(1 if request.GET.get('page', 1) == '' else request.GET.get('page', 1))

    if filter_method is not None:
        query = 'SELECT DISTINCT * FROM (SELECT id_barang, nama_item, warna, kondisi, nama_kategori FROM BARANG NATURAL JOIN KATEGORI_ITEM WHERE nama_kategori=\'{}\') AS N ORDER BY {}'.format(
            filter_method, sort_method)
    else:
        query = 'SELECT DISTINCT * FROM (SELECT id_barang, nama_item, warna, kondisi FROM BARANG NATURAL JOIN KATEGORI_ITEM) AS N ORDER BY {}'.format(
            sort_method)

    list_kategori = [
        {
            'nama': i.nama
        } for i in kategori
    ]
    barang = list(KategoriItem.objects.raw(query))
    data_barang = [
        {
            'id': i.id_barang,
            'nama': i.nama_item.nama,
            'warna': i.warna,
            'kondisi': i.kondisi
        } for i in barang
    ]
    return render(request, 'display_barang.html', {'barang': page_split(data_barang, page_number - 1), 'kategori': list_kategori, 'page': page_number,
        'pages': range(1, (len(data_barang) // page_size) + 1, )
})

def detail_barang(request, id):
    barang = Barang.objects.raw('SELECT * FROM BARANG WHERE id_barang = %s', [id])
    info = InfoBarangLevel.objects.raw('SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s', [id])
    levels = LevelKeanggotaan.objects.raw('SELECT * FROM LEVEL_KEANGGOTAAN')
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT BARANG_DIKIRIM.review, BARANG_DIKIRIM.tanggal_review FROM BARANG_DIKIRIM WHERE id_barang = %s',
            [id])
        review = cursor.fetchall()
    formset = formset_factory(FormInfoBarangLevel, extra=len(info), max_num=len(info))
    initial_barang = {
        'id_barang': barang[0].id_barang,
        'nama_item': barang[0].nama_item.nama,
        'warna': barang[0].warna,
        'url_foto': barang[0].url_foto,
        'kondisi': barang[0].kondisi,
        'lama_penggunaan': barang[0].lama_penggunaan,
        'no_ktp_penyewa': barang[0].no_ktp_penyewa.no_ktp.no_ktp
    }
    level = []
    initial_info = []
    for l in levels:
        exists = False
        for i in info:
            if l == i.nama_level:
                level.append(i.nama_level)
                initial_info.append({
                    'harga_sewa': i.harga_sewa,
                    'porsi_royalti': i.porsi_royalti
                })
                exists = True
                break
        if not exists:
            level.append(l)
            initial_info.append({
                'harga_sewa': '',
                'porsi_royalti': ''
            })
    level.reverse()
    form_barang = FormBarang(initial=initial_barang)
    for i in form_barang:
        i.field.disabled = True
    form_info = formset(prefix='info', initial=initial_info)
    for form in form_info:
        for f in form:
            f.field.disabled = True
    return render(request, 'detail_barang.html', {
        'barang': form_barang,
        'info': form_info,
        'level': level,
        'review': review
    })

def page_split(collection, page_number):
    if collection is None or len(collection) == 0:
        return None
    return list(chunk(collection))[page_number]


def chunk(collection):
    for i in range(0, len(collection), page_size):
        yield collection[i:i + page_size]

barang/templates/create_barang.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    {{ judul }} Barang
{% endblock title %}

{% block css %}
    <link href="{% static 'css/display_barang.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/form_create_barang.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
    <div class="py-5 text-center section-dark">
        <div class="container">
            <div class="row">
                <div class="bg-white p-5 my-5 mx-auto col-12 col-md-12">
                    <h1 class="mb-4 text-primary">Form {{ judul }} Barang</h1>
                    <form method="post">
                    {% csrf_token %}
                        <h5 style="color: black; text-align: left; font-weight: bold">Detail Barang</h5>
                        {% for field in barang %}
                            <div class="form-group row">
                                <label style="text-align: left; color: black" class="col-sm-3 col-form-label">{{ field.label }}</label>
                                <div class="input-group col-sm-9">
                                    {{ field.as_widget }}
                                    {% if field.label == 'Lama Penggunaan' %}
                                    <div class="input-group-append">
                                        <label class="input-group-text">bulan</label>
                                    </div>
                            {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <h5 style="color: black; text-align: left; font-weight: bold">Info Barang</h5>
                        {% for field in info %}
                            <div class="form-group row">
                                <label style="text-align: left; color: black" class="col-sm-3 col-form-label">{{ level.pop }}</label>
                                <div class="col-sm-9">
                                    <div class="form-row">
                                        <div class="col-sm-4 input-group">
                                            {{ field.porsi_royalti }}
                                            <div class="input-group-append">
                                                <label class="input-group-text">%</label>
                                            </div>
                                        </div>
                                        <div class="col input-group">
                                            <div class="input-group-prepend">
                                                <label class="input-group-text">Rp.</label>
                                            </div>
                                            {{ field.harga_sewa }}
                                            <div class="input-group-append">
                                                <label class="input-group-text">/ minggu</label>
                                            </div>
                                          </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {{ info.management_form }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
     <script type="text/javascript">
            $(function() {
                $('.formset').formset({
                    prefix: '{{ info.prefix }}'
                });
            })
        </script>

{% endblock script %}

barang/templates/detail_barang.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    Detail Barang
{% endblock title %}

{% block css %}
    <link href="{% static 'css/display_barang.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/form_create_barang.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/review.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
    <div class="py-5 text-center section-dark">
        <div class="container">
            <div class="row">
                <div class="bg-white p-5 my-5 mx-auto col-12 col-md-12">
                    <h1 class="mb-4 text-primary">Detail Barang</h1>
                    {% csrf_token %}
                    <form action="{% url 'pesanan:pesanan_anggota' %}">
                        {% for field in barang %}
                            <div class="form-group row">
                                <label style="text-align: left; color: black" class="col-sm-3 col-form-label">{{ field.label }}</label>
                                <div class="input-group col-sm-9">
                                    {{ field.as_widget }}
                                    {% if field.label == 'Lama Penggunaan' %}
                                    <div class="input-group-append">
                                        <label class="input-group-text">bulan</label>
                                    </div>
                            {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <h5 style="color: black; text-align: left; font-weight: bold">Info Barang</h5>
                        {% for field in info %}
                            <div class="form-group row">
                                <label style="text-align: left; color: black" class="col-sm-3 col-form-label">{{ level.pop }}</label>
                                <div class="col-sm-9">
                                    <div class="form-row">
                                        <div class="col-sm-4 input-group">
                                            {{ field.porsi_royalti }}
                                            <div class="input-group-append">
                                                <label class="input-group-text">%</label>
                                            </div>
                                        </div>
                                        <div class="col input-group">
                                            <div class="input-group-prepend">
                                                <label class="input-group-text">Rp.</label>
                                            </div>
                                            {{ field.harga_sewa }}
                                            <div class="input-group-append">
                                                <label class="input-group-text">/ minggu</label>
                                            </div>
                                          </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <h5 style="color: black; text-align: left; font-weight: bold">Review</h5>
                        <div id="message" style="margin-top: 20px">
                            {% if review %}
                                {% for r in review %}
                                <div class="message-child" id="{{ forloop.counter }}">
                                    <div class= "container">
                                        <div class="message-content">
                                            <p>{{ r.0 }}</p>
                                        </div>
                                        <div class="message-date">
                                            <p style="font-style: italic; font-size: 12px">Ditulis pada {{ r.1 }}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            {% else %}
                                <p style="color: black; font-style: italic; text-align: left">Belum ada review</p>
                            {% endif %}
                        </div>
                        {{ info.management_form }}
                        <button class="btn btn-primary">Pesan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
     <script type="text/javascript">
            $(function() {
                $('.formset').formset({
                    prefix: '{{ info.prefix }}'
                });
            })
        </script>

{% endblock script %}

barang/templates/display_barang.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    Barang
{% endblock title %}

{% block css %}
    <link href="{% static 'css/display_barang.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/checkbox.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/sort_filter_script.js' %}" rel="script" type="text/javascript"></script>
{% endblock css %}

{% block content %}
    <div class="py-5 text-center section-dark">
        <div class="container">
            <div class="row">
                <div class="bg-white p-5 my-5 mx-auto col-12 col-md-12">
                    <h1 class="mb-4 text-primary">Daftar Barang</h1>
                    <form class="mb-3" method="GET">
                        <div class="form-row align-items-center justify-content-center">
                            <div class="col-sm-3 my-1">
                                <select class="custom-select" id="sort-field" name="sort">
                                    <option {% if sort == 'id_barang' %}selected{% endif %} value="">Sort by</option>
                                    <option {% if sort == 'nama_item' %}selected{% endif %} value="nama_item">Nama</option>
                                    <option {% if sort == 'warna' %}selected{% endif %} value="warna">Warna</option>
                                </select>
                            </div>
                            <div class="col-sm-3 my-1">
                                <select class="custom-select" id="filter-field" name="filter">
                                    <option selected value="">Filter by</option>
                                    {% for k in kategori %}
                                        <option {% if filter == k.nama %}selected{% endif %} value="{{ k.nama }}">{{ k.nama }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table mt-4">
                            <thead class="text-dark">
                                <tr>
                                    <th>ID Barang</th>
                                    <th>Nama Barang</th>
                                    <th>Warna</th>
                                    <th>Kondisi</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody class="text-muted">
                                {% for i in barang %}
                                <tr>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.nama }}</td>
                                    <td>{{ i.warna }}</td>
                                    <td>{{ i.kondisi }}</td>
                                    <td>
                                    {% if request.session.role == 'admin' %}
                                        <div class="pi-draggable btn-group" draggable="true">
                                            <a href="{% url 'barang:detail_barang' id=i.id %}" class="btn btn-primary">Detail</a>
                                            <a href="{% url 'barang:update_barang' id=i.id %}" class="btn btn-warning">Update</a>
                                            <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#deletePopUp{{ forloop.counter }}">Delete</a>
                                        </div>
                                        <div class="modal fade" id="deletePopUp{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="deletePopUp" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header d-flex justify-content-center">
                                                        <h3 class="modal-title">Delete</h3>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div>Apakah anda yakin ingin menghapus barang ini?</div>
                                                        <div class="d-flex justify-content-center m-3">
                                                            <div class="pi-draggable btn-group mr-2" draggable="true"> <a href="{% url 'barang:delete_barang' id=i.id %}" class="btn btn-danger">Iya</a></div>
                                                            <div class="pi-draggable btn-group" draggable="true"> <a href="#" class="btn btn-primary" data-dismiss="modal">Tidak</a></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% else %}
                                            <div class="pi-draggable btn-group" id="tombol-detail" draggable="true">
                                                <a href="{% url 'barang:detail_barang' id=i.id %}" class="btn btn-primary">Detail</a>
                                            </div>
                                            <div class="form-group row" style="margin-bottom: auto">
                                                <div class="col-sm-8">
                                                    <input type="checkbox" name="checkboxes{{ forloop.counter }}" id="{{ forloop.counter }}" autocomplete="off"/>
                                                    <div class="btn-group">
                                                        <label for="{{ forloop.counter }}" class="btn btn-link">
                                                            <span class="fa fa-check-square-o fa-lg"></span>
                                                            <span class="fa fa-square-o fa-lg"></span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                    {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <nav>
                            <ul class="pagination justify-content-center mt-3" id="page-field">
                                {% for p in pages %}
                                    <li class="page-item">
                                        <button class="page-link {% if page == p %}text-white bg-info{% else %}text-info{% endif %}">{{ p }}</button>
                                    </li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}