barang/urls.py
from django.urls import path
from .views import *
app_name = 'barang'
urlpatterns = [
    path('daftar_barang', display_barang, name='daftar_barang'),
	path('detail_barang/<str:id>', detail_barang, name='detail_barang'),
	path('delete_barang/<str:id>', delete_barang, name='delete_barang'),
    path('update_barang/<str:id>', update_barang, name='update_barang'),
    path('create_barang', create_barang, name='create_barang'),
]

chat/urls.py
from django.urls import path
from .views import *
app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
    path('list-admin', list_chat_admin, name='list-chat')
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'
urlpatterns = [
	path('', display, name='display_item'),
	path('add/', add_item, name='add_item'),
	path('delete_item/<str:nama>/', delete_item, name='delete_item'),
	path('pilih_item/<str:nama>/', pilih_item, name='pilih_item'),
	path('update_item/<str:nama>/', update_item, name='update_item'),
]

toys_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import level.urls
import pesanan.urls
import item.urls
import pengiriman.urls
import barang.urls
import chat.urls
import login.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', include(main.urls)),
    path('barang/', include(barang.urls)),
    path('level/', include(level.urls)),
    path('pesanan/', include(pesanan.urls)),
    path('item/', include(item.urls)),
    path('pengiriman/', include(pengiriman.urls)),
    path('chat/', include(chat.urls)),
    path('login/', include(login.urls))
]

item/models.py
from django.db import models

# Create your models here.

item/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from .models import *

attrs_name = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nama lengkap Anda'
}

attrs_date = {
    'class': 'form-control',
    'size': 7,
    'type': 'date'
}

attrs_email = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan email valid Anda'
}

attrs_no_ktp = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nomer KTP Anda'
}

attrs_confirm = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nomer telepon Anda'
}

class Register_Form_Admin(forms.Form):
    no_ktp = forms.CharField(label='NO KTP', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nama_lengkap = forms.CharField(label='NAMA LENGKAP', required=True, widget=forms.widgets.TextInput(attrs=attrs_name))
    email = forms.EmailField(label='EMAIL', required=True, widget=forms.widgets.EmailInput(attrs=attrs_email))
    tanggal_lahir = forms.DateField(label='TANGGAL LAHIR', required=True, widget=forms.widgets.DateInput(attrs=attrs_date))
    nomor_telepon = forms.CharField(label='NOMOR TELEPON', required=True, widget=forms.widgets.TextInput(attrs=attrs_confirm))


class Register_Form_Anggota(forms.Form):
    no_ktp = forms.CharField(label='No KTP', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nama_lengkap = forms.CharField(label='Nama Lengkap', required=True, widget=forms.widgets.TextInput(attrs=attrs_name))
    email = forms.EmailField(label='Email', required=True, widget=forms.widgets.EmailInput(attrs=attrs_email))
    tanggal_lahir = forms.DateField(label='Tangal Lahir', required=True, widget=forms.widgets.DateInput(attrs=attrs_date))
    nomor_telepon = forms.CharField(label='Nomor Telepon', required=True, widget=forms.widgets.TextInput(attrs=attrs_confirm))
    nama_alamat = forms.CharField(label='Alamat', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    jalan = forms.CharField(label='Jalan', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nomor = forms.CharField(label='Nomer', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    kota = forms.CharField(label='Nama Kota', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    kode_post = forms.CharField(label='Kode Post', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))


class Login_Form(forms.Form):
    attrs_no_ktp = {
    'class' : 'form-control',
    'placeholder' : 'Nomer KTP',
    }

    attrs_email = {
    'class' : 'form-control',
    'placeholder' : 'email',
    }

    no_ktp = forms.CharField(label = 'NO KTP', required = True, widget = forms.widgets.TextInput(attrs = attrs_no_ktp))
    email = forms.EmailField(label = 'Email', required = True, widget = forms.widgets.EmailInput(attrs = attrs_email))

item/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db import connection

from toysrent_db.models import *
# Create your views here.
response = {'author':'toys-rent-e9'}
def display(request):
	item = list(Item.objects.raw('SELECT * FROM ITEM'))
	count = 1
	data = []
	for i in item:
		x = {
			'nomor' : count,
			'nama' : i.nama,
			'kategori' : i.deskripsi} 
		data.append(x)
		count = count+1
	response['item'] = data
	return render(request, 'display_item.html', response)


def add_item(request):
	if request.method == 'POST':
		nama = request.POST['nama_item']
		deskripsi = request.POST['deskripsi']
		rentang_usia = request.POST['rentang_usia'].split('-')
		usia_dari = int(rentang_usia[0])
		usia_sampai = int(rentang_usia[1])
		bahan = request.POST['bahan']
		with connection.cursor() as c:
			sql = "INSERT INTO item (nama, deskripsi, usia_dari, usia_sampai, bahan) VALUES ('%s','%s',%d,%d,'%s')" % (nama, deskripsi, usia_dari, usia_sampai, bahan)
			c.execute(sql)
			return HttpResponseRedirect(reverse('item:display_item'))
		return
	else:
		return render(request, 'tambah_item.html', response)

def delete_item(request, nama):
	with connection.cursor() as c:
		c.execute("DELETE FROM item WHERE nama= %s", [nama])
		return HttpResponseRedirect(reverse('item:display_item'))

	return render(request, 'tambah_item.html', response)

def update_item(request):
	return render(request, 'update_item.html', response)


def pilih_item(request, nama):
	select_item = list(Item.objects.raw('SELECT * FROM ITEM WHERE nama = %s', [nama]))
	item = []
	for x in select_item:
		data = {
			'nama': x.nama,
			'deskripsi' : x.deskripsi,
			'rentang_usia' : str(x.usia_dari) + '-' + str(x.usia_sampai),
			'bahan': x.bahan 
		}
		item.append(data)
	response['item'] = item
	return render(request, 'update_item.html', response)

item/templates/display_item.html
<!DOCTYPE html>
{% extends 'layout/base.html' %}

{% load static %}
{% load staticfiles %}

{% block title %}
Item
{% endblock title %}

{% block css %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- PAGE settings -->
<meta name="description" content="Toys rent E9">
<meta name="keywords" content="Hehehe">
<!-- CSS dependencies -->
<link href="{% static 'aquamarine.css' %}" rel="stylesheet" type="text/css">
<!-- Script: Make my navbar transparent when the document is scrolled to top -->
<script src="{% static 'navbar-ontop.js' %}"></script>
<!-- Script: Animated entrance -->
<script src="{% static 'animate-in.js' %}"></script>

{% endblock css %}

{% block content %}

<body class="h-100 w-100">

  <!-- Action From-->
  <!-- Modal Login-->
  <!-- Content -->
  <div class="py-5 text-center section-dark" style="  background-image: url(&quot;https://www.smeportal.sg/content/tech-depot/en/tech-solutions/data-analytics/collection-delivery-management-system-cdms/_jcr_content/topContent/image.img.jpg/1520986706766.jpg&quot;); background-size: cover; background-position: top left;  background-repeat: repeat;">
    <div class="container">
      <div class="row">
        <div class="bg-white p-5 my-5 mx-auto col-12 col-md-12" style="">
          <h1 class="mb-4 text-primary">Daftar Item</h1>
          <div class="btn-group">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Sort by </button>
            <div class="dropdown-menu"> <a class="dropdown-item" href="#">ID Pengirman</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Tanggal Pengiriman</a>
            </div>
          </div>
          <div class="table-responsive" style="">
            <table class="table mt-4">
              <thead class = "text-dark">
                <tr>
                  <th>No</th>
                  <th>Nama Item</th>
                  <th>Kategori</th>
                  {% if false%}
                    <th>Action</th>
                  {% else %}
                    <th>Action</th>
                    <th>Action</th>
                  {% endif %}
                </tr>
              </thead>
              <tbody class = "text-muted">
                {% for i in item %}
                  <tr class="h-100">
                    <td class="align-middle">{{ i.nomor }}</td>
                    <td class="align-middle">{{ i.nama }}</td>
                    <td class="align-middle">{{ i.kategori }}</td>
                    {% if request.session.role == 'anggota' %}
                      <td>
                        <div class="pi-draggable btn-group" draggable="true"> <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#viewPopUp">View</a></div>
                      </td>
                    {% else %}
                      <div class="btn-group">
                        <td style="vertical-align: middle">
                          <div class="pi-draggable btn-group" draggable="true"> <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#viewPopUp">View</a></div>
                        </td>
                        <td class="btn-group-vertical">
                          <div class="pi-draggable button-group" role="group" draggable="true">

                            <!--INSERT DATA - FALSE-->
                            <form class="mb-1" action="{% url 'barang:create_barang' %}">
                              <button class="btn btn-primary">Insert</button>
                            </form>
                            
                            
                            <!--UPDATE DATA-->
                            <form class="mb-1" action="{% url 'item:pilih_item' nama=i.nama %}">
                              <button class="btn btn-warning">Update</button>
                            </form>

                            
                            <!--DELETE DATA-->
                            <form class="mb-1" action="#">
                              <button class="btn btn-danger" data-toggle="modal" data-target="#deletePopUp{{ forloop.counter }}">Delete</button>
                            </form>
                            <div class="modal fade" id="deletePopUp{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="deletePopUp" tabindex="-1" role="dialog" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                  <div class="modal-header d-flex justify-content-center">
                                    <h3 class="modal-title">Delete</h3>
                                  </div>
                                  <div class="modal-body">
                                    <div>Apakah anda yakin ingin menghapus item ini?</div>
                                    <div class="d-flex justify-content-center m-3">
                                    <div class="pi-draggable btn-group mr-2" draggable="true"> <a href="{% url 'item:delete_item' nama=i.nama %}" class="btn btn-danger">Iya</a></div>
                                    <div class="pi-draggable btn-group" draggable="true"> <a href="#" class="btn btn-primary">Tidak</a></div>
                                    </div>
                                  </div>
                                </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </td>
                      </div>
                    {% endif %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <ul class="pagination">
            <li class="page-item"> <a class="page-link" href="#"> <span>«</span></a> </li>
            <li class="page-item active"> <a class="page-link" href="#">1</a> </li>
            <li class="page-item"> <a class="page-link" href="#">2</a> </li>
            <li class="page-item"> <a class="page-link" href="#">3</a> </li>
            <li class="page-item"> <a class="page-link" href="#">4</a> </li>
            <li class="page-item"> <a class="page-link" href="#"> <span>»</span></a> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Action From-->
  <!-- Modal Register-->
  <div class="modal fade" id="viewPopUp" tabindex="-1" role="dialog" aria-labelledby="viewPopUp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header d-flex justify-content-center">
          <h3 class="modal-title">View</h3>
        </div>
        <div class="modal-body text-center d-flex justify-content-center">
          <div class="btn-group-vertical">
            <div>
              <form class="mb-2 mt-2" action=#>
                <button class="btn btn-primary">Yes</button>
              </form>
              <form>
                <button class="btn btn-primary" formaction=#>No</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal-->
  <!-- Modal Register-->
  <!-- JavaScript dependencies -->
  <!-- Script: Smooth scrolling between anchors in the same page -->
</body>
{% endblock content %}

item/templates/tambah_item.html
{% extends 'layout/base.html' %}

{% load static %}
{% load staticfiles %}

{% block title %}
Add Item
{% endblock title %}

{% block css %}

{% endblock css %}

{% block content %}
<body class="h-100 w-100">
  <div class="py-5 text-center section-dark" style="	background-image: url(&quot;https://www.smeportal.sg/content/tech-depot/en/tech-solutions/data-analytics/collection-delivery-management-system-cdms/_jcr_content/topContent/image.img.jpg/1520986706766.jpg&quot;);	background-size: cover;	background-position: top left;	background-repeat: repeat;">
    <div class="container">
      <div class="row">
        <div class="bg-white p-5 my-5 mx-auto col-6 col-md-7 border" style="border-radius: 24px">
          <h1 class="mb-4 text-primary">Create New Item</h1>
          <form method="POST" action="{% url 'item:add_item' %}">
          	{% csrf_token %}
            <div class="form-group"><label class="text-muted">Nama</label>
              <div class="input-group"><input type="text" class="form-control" name="nama_item" id="nama_item" placeholder="ex: nama"></div>
            </div>
            <div class="form-group"><label class="text-muted">Deskripsi</label>
              <div class="input-group"><input type="text" class="form-control" name="deskripsi" id="deskripsi" placeholder="deskripsi item">
              </div>
            </div>
            <div class="form-group"><label class="text-muted">Rentang Usia</label>
              <div class="input-group"><input type="text" class="form-control" name="rentang_usia" id="rentang_usia" placeholder="ex: 5 - 10"></div>
            </div>
            <div class="form-group"><label class="text-muted">Bahan</label>
              <div class="input-group"><input type="text" class="form-control" name="bahan" id="bahan" placeholder="Nama bahan"></div>
            </div>
            <div class="form-group"><label class="text-muted text-left">Kategori</label><select class="custom-select">
                <option selected="">Choose category</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</body>
{% endblock content %}

item/templates/update_item.html
{% extends 'layout/base.html' %}

{% load static %}
{% load staticfiles %}

{% block title %}
Add Item
{% endblock title %}

{% block css %}

{% endblock css %}

{% block content %}
<body class="h-100 w-100">
  <div class="py-5 text-center section-dark" style="	background-image: url(&quot;https://www.smeportal.sg/content/tech-depot/en/tech-solutions/data-analytics/collection-delivery-management-system-cdms/_jcr_content/topContent/image.img.jpg/1520986706766.jpg&quot;);	background-size: cover;	background-position: top left;	background-repeat: repeat;">
    <div class="container">
      <div class="row">
        <div class="bg-white p-5 my-5 mx-auto col-6 col-md-7 border" style="border-radius: 24px">
          <h1 class="mb-4 text-primary">Create New Item</h1>
          <form method="POST" action="{% url 'item:add_item' %}">
          	{% csrf_token %}
            {% for x in item %}
            <div class="form-group"><label class="text-muted">Nama</label>
              <div class="input-group"><input type="text" class="form-control" name="nama_item" id="nama_item" value="{{ x.nama }}"></div>
            </div>
            <div class="form-group"><label class="text-muted">Deskripsi</label>
              <div class="input-group"><input type="text" class="form-control" name="deskripsi" id="deskripsi" value="{{ x.deskripsi }}">
              </div>
            </div>
            <div class="form-group"><label class="text-muted">Rentang Usia</label>
              <div class="input-group"><input type="text" class="form-control" name="rentang_usia" id="rentang_usia" value="{{ x.rentang_usia }}"></div>
            </div>
            <div class="form-group"><label class="text-muted">Bahan</label>
              <div class="input-group"><input type="text" class="form-control" name="bahan" id="bahan" value="{{ x.bahan }}"></div>
            </div>
            <div class="form-group"><label class="text-muted text-left">Kategori</label>
              <div class="input-group"><input type="text" class="form-control" name="kategori" id="kategori" value="kategori"></div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            {% endfor %}
          </form>

        </div>
      </div>
    </div>
  </div>
</body>
{% endblock content %}