barang/urls.py
from django.urls import path
from .views import *
app_name = 'barang'
urlpatterns = [
    path('daftar_barang', display_barang, name='daftar_barang'),
	path('detail_barang/<str:id>', detail_barang, name='detail_barang'),
	path('delete_barang/<str:id>', delete_barang, name='delete_barang'),
    path('update_barang/<str:id>', update_barang, name='update_barang'),
    path('create_barang', create_barang, name='create_barang'),
]

chat/urls.py
from django.urls import path
from .views import *
app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
    path('list-admin', list_chat_admin, name='list-chat')
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'
urlpatterns = [
	path('', display, name='display_item'),
	path('add/', add_item, name='add_item'),
	path('delete_item/<str:nama>/', delete_item, name='delete_item'),
	path('pilih_item/<str:nama>/', pilih_item, name='pilih_item'),
	path('update_item/<str:nama>/', update_item, name='update_item'),
]

level/urls.py
from django.urls import path
from .views import *

app_name = 'level'
urlpatterns = [
    path('', createlevel, name='createlevel'),
    path('daftar_level', daftarlevel, name='daftarlevel'),
    path('update_level', updatelevel, name='updatelevel'),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
	path('', auth_login , name='auth'),
	path('logout', logout, name='logout'),   
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
	path('', index, name='index'),
	path('admin', reg_admin, name="admin"),
	path('anggota', reg_anggota, name="anggota"),
	path('reg_admin', save_admin, name="register_admin"),
	path('reg_anggota', save_anggota, name="register_anggota"),   
]

toys_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import level.urls
import pesanan.urls
import item.urls
import pengiriman.urls
import barang.urls
import chat.urls
import login.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', include(main.urls)),
    path('barang/', include(barang.urls)),
    path('level/', include(level.urls)),
    path('pesanan/', include(pesanan.urls)),
    path('item/', include(item.urls)),
    path('pengiriman/', include(pengiriman.urls)),
    path('chat/', include(chat.urls)),
    path('login/', include(login.urls))
]

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Login(models.Model):
	"""docstring for ClassName"""
	no_ktp = models.CharField(max_length=100)
	email = models.EmailField(max_length=50)

class Register_Admin(models.Model):
    no_ktp = models.CharField(max_length=100, unique = True)
    nama_lengkap = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 50, unique = True, default = False)
    tanggal_lahir = models.DateField()
    nomor_telepon = models.CharField(max_length = 100)

class Register_Anggota(models.Model):
	"""docstring for ClassName"""
	pengguna = models.ForeignKey('Register_Admin', on_delete = models.CASCADE)
	alamat = models.ForeignKey('Alamat', on_delete = models.CASCADE)

		
class Alamat(models.Model):
	"""docstring for ClassName"""
	nama_alamat = models.CharField(max_length=50)
	jalan = models.CharField(max_length=50)
	nomor = models.CharField(max_length=50)
	kota = models.CharField(max_length=50)
	kode_post = models.CharField(max_length=50)

main/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from .models import *

attrs_name = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nama lengkap Anda'
}

attrs_date = {
    'class': 'form-control',
    'size': 7,
    'type': 'date'
}

attrs_email = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan email valid Anda'
}

attrs_no_ktp = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nomer KTP Anda'
}

attrs_confirm = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nomer telepon Anda'
}

class Register_Form_Admin(forms.Form):
    no_ktp = forms.CharField(label='NO KTP', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nama_lengkap = forms.CharField(label='NAMA LENGKAP', required=True, widget=forms.widgets.TextInput(attrs=attrs_name))
    email = forms.EmailField(label='EMAIL', required=True, widget=forms.widgets.EmailInput(attrs=attrs_email))
    tanggal_lahir = forms.DateField(label='TANGGAL LAHIR', required=True, widget=forms.widgets.DateInput(attrs=attrs_date))
    nomor_telepon = forms.CharField(label='NOMOR TELEPON', required=True, widget=forms.widgets.TextInput(attrs=attrs_confirm))


class Register_Form_Anggota(forms.Form):
    no_ktp = forms.CharField(label='No KTP', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nama_lengkap = forms.CharField(label='Nama Lengkap', required=True, widget=forms.widgets.TextInput(attrs=attrs_name))
    email = forms.EmailField(label='Email', required=True, widget=forms.widgets.EmailInput(attrs=attrs_email))
    tanggal_lahir = forms.DateField(label='Tangal Lahir', required=True, widget=forms.widgets.DateInput(attrs=attrs_date))
    nomor_telepon = forms.CharField(label='Nomor Telepon', required=True, widget=forms.widgets.TextInput(attrs=attrs_confirm))
    nama_alamat = forms.CharField(label='Alamat', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    jalan = forms.CharField(label='Jalan', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nomor = forms.CharField(label='Nomer', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    kota = forms.CharField(label='Nama Kota', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    kode_pos = forms.CharField(label='Kode Post', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))


class Login_Form(forms.Form):
    attrs_no_ktp = {
    'class' : 'form-control',
    'placeholder' : 'Nomer KTP',
    }

    attrs_email = {
    'class' : 'form-control',
    'placeholder' : 'email',
    }

    no_ktp = forms.CharField(label = 'NO KTP', required = True, widget = forms.widgets.TextInput(attrs = attrs_no_ktp))
    email = forms.EmailField(label = 'Email', required = True, widget = forms.widgets.EmailInput(attrs = attrs_email))

main/views.py
from django.shortcuts import render
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection
from toysrent_db.models import *

# Create your views here.
response = {'author':'admin-toys-rent'}
response['login'] = Login_Form
def index(request):
	return render(request, 'main.html', response)

def reg_admin(request):
	response['regis'] = Register_Form_Admin
	return render(request, 'register_for_admin.html', response)

def reg_anggota(request):
	response['regis'] = Register_Form_Anggota
	return render(request, 'register_for_anggota.html', response)

def save_admin(request):
	if request.method == 'POST':
		no_ktp = request.POST['no_ktp']
		nama = request.POST['nama_lengkap']
		email = request.POST['email']
		tanggal_lahir = request.POST['tanggal_lahir']
		no_telp = request.POST['nomor_telepon']
		request.session['role'] = 'admin'
		request.session['no_ktp'] = no_ktp
		with connection.cursor() as c:
			ktp_admin = "INSERT INTO ADMIN VALUES('%s')" % (no_ktp)
			sql = "INSERT INTO PENGGUNA (no_ktp, nama_lengkap, email, tanggal_lahir, no_telp) VALUES ('%s', '%s', '%s', '%s', '%s')" % (no_ktp, nama, email, tanggal_lahir, no_telp)
			c.execute(sql)
			c.execute(ktp_admin)
			return HttpResponseRedirect(reverse('login:auth')) #return pada admin
		#return default

def save_anggota(request):
	if request.method == 'POST':
		no_ktp = request.POST['no_ktp']
		nama = request.POST['nama_lengkap']
		email = request.POST['email']
		tanggal_lahir = request.POST['tanggal_lahir']
		no_telp = request.POST['nomor_telepon']
		nama_alamat = request.POST['nama_alamat']
		jalan = request.POST['jalan']
		nomor = request.POST['nomor']
		kota = request.POST['kota']
		kodepos = request.POST['kode_pos']
		request.session['role'] = 'anggota'
		request.session['no_ktp'] = no_ktp
		with connection.cursor() as c:
			alamat = "INSERT INTO ALAMAT VALUES ('%s', '%s', '%s', '%s', '%s', '%s')" % (no_ktp, nama_alamat, jalan, nomor, kota, kodepos)
			data = "INSERT INTO PENGGUNA (no_ktp, nama_lengkap, email, tanggal_lahir, no_telp) VALUES ('%s', '%s', '%s', '%s', '%s')" % (no_ktp, nama, email, tanggal_lahir, no_telp)
			anggota = "INSERT INTO ANGGOTA VALUES ('%s', 0, 'Bronze')" % (no_ktp)
			c.execute(data)
			c.execute(anggota)
			c.execute(alamat)
			return HttpResponseRedirect(reverse('login:auth'))


	

main/templates/partials/footer.html
<footer class="text-md-left text-center p-4 bg-dark text-light">
    <div class="container">
      <div class="row">
        <div class="my-3 col-lg-4 col-md-6">
          <h3>Toys Rent E9</h3>
          <p class="text-muted">May 2019</p>
          <p class="my-3">Fakultas Ilmu Komputer<br>Universitas Indonesia</p>
          <a class="btn btn-lg btn-primary" href="#">Register now</a>
        </div>
        <div class="my-3 col-lg-4 col-md-6">
          <h3>Reach us!</h3>
          <form>
            <fieldset class="form-group my-3">
              <input type="email" class="form-control" id="Input Email" placeholder="Email"> </fieldset>
            <fieldset class="form-group my-3">
              <input type="message" class="form-control" id="Input Message" placeholder="Message"> </fieldset>
            <button type="submit" class="btn btn-outline-primary">Submit</button>
          </form>
        </div>
        <div class="col-lg-1"> </div>
        <div class="my-3 col-lg-3">
          <h3>Follow</h3>
          <a href="https://www.facebook.com" target="blank"><i class="fa fa-facebook-square text-muted fa-3x m-2"></i></a>
          <a href="https://www.instagram.com" target="blank"><i class="fa fa-3x fa-instagram text-muted m-2"></i></a>
          <a href="https://twitter.com" target="blank"><i class="fa fa-3x fa-twitter m-2 text-muted"></i></a>
          <a href="https://plus.google.com" target="blank"><i class="fa fa-3x fa-google-plus-official text-muted m-2"></i></a>
          <a href="https://pinterest.com" target="blank"><i class="fa fa-3x text-muted fa-pinterest-p m-2"></i></a>
          <a href="https://www.youtube.com" target="blank"><i class="fa fa-3x text-muted fa-youtube-play m-2"></i></a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="text-muted">© Copyright 2019 E9 - All rights reserved. </p>
        </div>
      </div>
    </div>
  </footer>

main/templates/partials/header.html
{% load static %}
{% if request.session.role == 'admin' %}
  <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Item&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'item:add_item' %}">Tambah Item</a><a class="dropdown-item" href="{% url 'item:display_item' %}">Daftar Item</a> </div>
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Barang&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'barang:create_barang' %}">Tambah Barang</a> <a class="dropdown-item" href="{% url 'barang:daftar_barang' %}">Daftar Barang</a> </div>
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Level&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'level:createlevel' %}">Tambah Level</a> <a class="dropdown-item" href="{% url 'level:daftarlevel' %}">Daftar Level</a> </div>
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pesanan&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'pesanan:pesanan_admin' %}">Buat Pesanan</a> <a class="dropdown-item" href="{% url 'pesanan:pesanan_admin' %}">Daftar Pesanan</a> </div>
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pengiriman&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'pengiriman:add_pengiriman' %}">Buat Pengiriman</a> <a class="dropdown-item" href="{% url 'pengiriman:daftar_pengiriman' %}">Daftar Pengiriman</a> </div>
            </li>
            <li class="nav-item mx-2" style="">
              <a class="nav-link" href="{% url 'chat:list-chat' %}">Chat</a>
            </li>
            <li class="nav-item mx-2" style="">
              <a class="nav-link" href="{% url 'pengiriman:daftar_review' %}">Review</a>
            </li>
            <a class="btn navbar-btn mx-2 text-white btn-outline-light" href="{% url 'login:logout' %}">Logout</a>
          </ul>
        </div>
      </div>
    </nav>
{% else %}
  <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item mx-2" style="">
              <a class="nav-link" href="{% url 'item:display_item' %}">Daftar Item</a>
            </li>
            <li class="nav-item mx-2" style="">
              <a class="nav-link" href="{% url 'barang:daftar_barang' %}">Daftar Barang</a>
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pesanan&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'pesanan:pesanan_anggota' %}">Buat Pesanan</a> <a class="dropdown-item" href="{% url 'pesanan:daftar_pesanan_anggota' %}">Daftar Pesanan</a> </div>
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pengiriman&nbsp;</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="{% url 'pengiriman:add_pengiriman' %}">Buat Pengiriman</a> <a class="dropdown-item" href="{% url 'pengiriman:daftar_pengiriman' %}">Daftar Pengiriman</a> </div>
            </li>
            <li class="nav-item mx-2" style="">
              <a class="nav-link" href="{% url 'chat:chat' %}">Chat</a>
            </li>
            <li class="nav-item mx-2" style="">
              <a class="nav-link" href="{% url 'pengiriman:daftar_review' %}">Review</a>
            </li><a class="btn navbar-btn mx-2 text-white btn-outline-light" href="{% url 'login:logout' %}">Logout</a>
          </ul>
        </div>
      </nav>

  {% endif %}

main/templates/partials/source.html
{% load static %}
<link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

<link href="{% static 'css/base.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/header.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/footer.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/aquamarine.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/landing.css' %}" rel="stylesheet" type="text/css">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script src="{% static 'js/animate-in.js' %}"></script>
<script src="{% static 'js/navbar-ontop.js' %}"></script>
<script src="{% static 'js/smooth-scroll.js' %}"></script>