chat/urls.py
from django.urls import path
from .views import *
app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
    path('list-admin', list_chat_admin, name='list-chat')
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
	path('', auth_login , name='auth'),
	path('logout', logout, name='logout'),   
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
	path('', index, name='index'),
	path('admin', reg_admin, name="admin"),
	path('anggota', reg_anggota, name="anggota"),
	path('reg_admin', save_admin, name="register_admin"),
	path('reg_anggota', save_anggota, name="register_anggota"),   
]

toys_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import level.urls
import pesanan.urls
import item.urls
import pengiriman.urls
import barang.urls
import chat.urls
import login.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', include(main.urls)),
    path('barang/', include(barang.urls)),
    path('level/', include(level.urls)),
    path('pesanan/', include(pesanan.urls)),
    path('item/', include(item.urls)),
    path('pengiriman/', include(pengiriman.urls)),
    path('chat/', include(chat.urls)),
    path('login/', include(login.urls))
]

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Login(models.Model):
	"""docstring for ClassName"""
	no_ktp = models.CharField(max_length=100)
	email = models.EmailField(max_length=50)

class Register_Admin(models.Model):
    no_ktp = models.CharField(max_length=100, unique = True)
    nama_lengkap = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 50, unique = True, default = False)
    tanggal_lahir = models.DateField()
    nomor_telepon = models.CharField(max_length = 100)

class Register_Anggota(models.Model):
	"""docstring for ClassName"""
	pengguna = models.ForeignKey('Register_Admin', on_delete = models.CASCADE)
	alamat = models.ForeignKey('Alamat', on_delete = models.CASCADE)

		
class Alamat(models.Model):
	"""docstring for ClassName"""
	nama_alamat = models.CharField(max_length=50)
	jalan = models.CharField(max_length=50)
	nomor = models.CharField(max_length=50)
	kota = models.CharField(max_length=50)
	kode_post = models.CharField(max_length=50)

main/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from .models import *

attrs_name = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nama lengkap Anda'
}

attrs_date = {
    'class': 'form-control',
    'size': 7,
    'type': 'date'
}

attrs_email = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan email valid Anda'
}

attrs_no_ktp = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nomer KTP Anda'
}

attrs_confirm = {
    'class': 'form-control',
    'size': 7,
    'placeholder': 'Masukkan nomer telepon Anda'
}

class Register_Form_Admin(forms.Form):
    no_ktp = forms.CharField(label='NO KTP', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nama_lengkap = forms.CharField(label='NAMA LENGKAP', required=True, widget=forms.widgets.TextInput(attrs=attrs_name))
    email = forms.EmailField(label='EMAIL', required=True, widget=forms.widgets.EmailInput(attrs=attrs_email))
    tanggal_lahir = forms.DateField(label='TANGGAL LAHIR', required=True, widget=forms.widgets.DateInput(attrs=attrs_date))
    nomor_telepon = forms.CharField(label='NOMOR TELEPON', required=True, widget=forms.widgets.TextInput(attrs=attrs_confirm))


class Register_Form_Anggota(forms.Form):
    no_ktp = forms.CharField(label='No KTP', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nama_lengkap = forms.CharField(label='Nama Lengkap', required=True, widget=forms.widgets.TextInput(attrs=attrs_name))
    email = forms.EmailField(label='Email', required=True, widget=forms.widgets.EmailInput(attrs=attrs_email))
    tanggal_lahir = forms.DateField(label='Tangal Lahir', required=True, widget=forms.widgets.DateInput(attrs=attrs_date))
    nomor_telepon = forms.CharField(label='Nomor Telepon', required=True, widget=forms.widgets.TextInput(attrs=attrs_confirm))
    nama_alamat = forms.CharField(label='Alamat', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    jalan = forms.CharField(label='Jalan', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    nomor = forms.CharField(label='Nomer', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    kota = forms.CharField(label='Nama Kota', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))
    kode_pos = forms.CharField(label='Kode Post', required=True, widget=forms.widgets.TextInput(attrs=attrs_no_ktp))


class Login_Form(forms.Form):
    attrs_no_ktp = {
    'class' : 'form-control',
    'placeholder' : 'Nomer KTP',
    }

    attrs_email = {
    'class' : 'form-control',
    'placeholder' : 'email',
    }

    no_ktp = forms.CharField(label = 'NO KTP', required = True, widget = forms.widgets.TextInput(attrs = attrs_no_ktp))
    email = forms.EmailField(label = 'Email', required = True, widget = forms.widgets.EmailInput(attrs = attrs_email))

main/views.py
from django.shortcuts import render
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection
from toysrent_db.models import *

# Create your views here.
response = {'author':'admin-toys-rent'}
response['login'] = Login_Form
def index(request):
	return render(request, 'main.html', response)

def reg_admin(request):
	response['regis'] = Register_Form_Admin
	return render(request, 'register_for_admin.html', response)

def reg_anggota(request):
	response['regis'] = Register_Form_Anggota
	return render(request, 'register_for_anggota.html', response)

def save_admin(request):
	if request.method == 'POST':
		no_ktp = request.POST['no_ktp']
		nama = request.POST['nama_lengkap']
		email = request.POST['email']
		tanggal_lahir = request.POST['tanggal_lahir']
		no_telp = request.POST['nomor_telepon']
		request.session['role'] = 'admin'
		request.session['no_ktp'] = no_ktp
		with connection.cursor() as c:
			ktp_admin = "INSERT INTO ADMIN VALUES('%s')" % (no_ktp)
			sql = "INSERT INTO PENGGUNA (no_ktp, nama_lengkap, email, tanggal_lahir, no_telp) VALUES ('%s', '%s', '%s', '%s', '%s')" % (no_ktp, nama, email, tanggal_lahir, no_telp)
			c.execute(sql)
			c.execute(ktp_admin)
			return HttpResponseRedirect(reverse('login:auth')) #return pada admin
		#return default

def save_anggota(request):
	if request.method == 'POST':
		no_ktp = request.POST['no_ktp']
		nama = request.POST['nama_lengkap']
		email = request.POST['email']
		tanggal_lahir = request.POST['tanggal_lahir']
		no_telp = request.POST['nomor_telepon']
		nama_alamat = request.POST['nama_alamat']
		jalan = request.POST['jalan']
		nomor = request.POST['nomor']
		kota = request.POST['kota']
		kodepos = request.POST['kode_pos']
		request.session['role'] = 'anggota'
		request.session['no_ktp'] = no_ktp
		with connection.cursor() as c:
			alamat = "INSERT INTO ALAMAT VALUES ('%s', '%s', '%s', '%s', '%s', '%s')" % (no_ktp, nama_alamat, jalan, nomor, kota, kodepos)
			data = "INSERT INTO PENGGUNA (no_ktp, nama_lengkap, email, tanggal_lahir, no_telp) VALUES ('%s', '%s', '%s', '%s', '%s')" % (no_ktp, nama, email, tanggal_lahir, no_telp)
			anggota = "INSERT INTO ANGGOTA VALUES ('%s', 0, 'Bronze')" % (no_ktp)
			c.execute(data)
			c.execute(anggota)
			c.execute(alamat)
			return HttpResponseRedirect(reverse('login:auth'))


	

main/templates/main.html
{% extends 'layout/base.html' %} {% load static %} {% block title %} Homepage {% endblock title %} {% block css %} {% endblock css %} {% block content %}


<body class="text-center">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home&nbsp;</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="#">About</a> <a class="dropdown-item" href="#">Gallery</a> <a class="dropdown-item" href="#" contenteditable="true">Team</a> </div>
                    </li>
                </ul>
                <a class="btn navbar-btn mx-2 text-white btn-outline-light" data-toggle="modal" data-target="#exampleModalCenter">Register now</a><a class="btn navbar-btn mx-2 text-white btn-outline-light" data-toggle="modal" data-target="#loginPopUp">Login</a>
            </div>
        </div>
    </nav>




    <!-- Action From-->
    <!-- Modal Login-->
    <div class="modal fade" id="loginPopUp" tabindex="-11" role="dialog" aria-labelledby="loginPopUp" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header d-flex justify-content-center">
                    <h3 class="modal-title">Login</h3>
                </div>
                <div class="modal-body">
                    <form id="regist" method="POST" action="{% url 'login:auth' %}">
                        {% csrf_token %} {{login}}
                        <div class="mt-3 d-flex justify-content-end">
                            <button class="btn btn-primary">Sign In</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-start">
                    <div>Don't you have an account? <a href="#" data-toggle="modal" data-target="#exampleModalCenter">Sign Up</a></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Register-->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header d-flex justify-content-center">
                    <h3 class="modal-title">Pick the Role</h3>
                </div>
                <div class="modal-body text-center d-flex justify-content-center">
                    <div class="btn-group-vertical">
                        <div>
                            <form class="mb-2 mt-2" action="{% url 'main:admin' %}">
                                <button class="btn btn-primary">Admin</button>
                            </form>
                            <form>
                                <button class="btn btn-primary" formaction="{% url 'main:anggota' %}">Anggota</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Cover -->
    <div class="d-flex align-items-center py-5 cover section-dark" id="landing">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-white mt-5">
                    <h1 class="display-2 d-none d-md-block" style="	text-shadow: 0px 3px 4px black;">Want to rent some toys?</h1>
                    <h1 class="display-4 d-block d-md-none">Conference Pingendo</h1>
                    <a class="btn btn-lg btn-outline-light mx-2 mt-4" data-toggle="modal" data-target="#loginPopUp">Login</a>
                    <a data-toggle="modal" data-target="#exampleModalCenter" class="btn btn-lg btn-outline-light mt-4 mx-2">Register</a><i class="d-block fa fa-angle-down pt-5 fa-3x"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- Parallax section -->
    <div class="py-5 section-parallax" id="abouttoys">
        <div class="container my-5 bg-light p-4">
            <div class="row mx-auto">
                <div class="col-md-12">
                    <h1 class="mb-3">About Toys Rent</h1>
                    <p class="">We are a couple of people&nbsp; who loves&nbsp; toys as much as you do.&nbsp;</p>
                </div>
            </div>
        </div>
    </div>
    <div class="py-5 section bg-faded bg-light" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="mb-4">Our Top Priorities</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-6">
                    <img class="center-block img-fluid d-block" src="{% static 'images/teddy-bear.svg' %}">

                    <h5 class=""><b>High Quality</b></h5>
                </div>
                <div class="col-md-3 col-6">
                    <img class="center-block img-fluid d-block" src="{% static 'images/credit-card.svg' %}">
                    <h5 class=""><b>Easy Payment</b></h5>
                </div>
                <div class="col-md-3 col-6">
                    <img class="center-block img-fluid d-block" src="{% static 'images/car.svg' %}">
                    <h5 class=""><b>Fast Delivery</b></h5>
                </div>
                <div class="col-md-3 col-6">
                    <img class="center-block img-fluid d-block" src="{% static 'images/smile.svg' %}">
                    <h5 class=""><b>Happy Customers</b></h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Speakers -->
    <!-- Sponsor logos -->
    <div class="py-5 bg-light" id="speakers">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h1 contenteditable="true"><b>Team</b></h1>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-md-4 animate-in-left col-lg-3" id="team">
                    <a href="#">
                        <img id="team" src="{% static 'images/alis.jpg' %}" class="center-block my-3 rounded-circle" width="300">
                        <h3 class="mb-0"><b>Alya Isti Safira</b></h3>
                        <p class="text-muted">Front-end Developer</p>
                    </a>
                </div>
                <div class="col-6 col-lg-3">
                    <a href="#">
                        <img id="team" src="{% static 'images/clarisa.jpg' %}" class="center-block my-3 rounded-circle" width="300">
                        <h3 class="mb-0"><b>Clarisa Mirah Sekarsari</b></h3>
                        <p class="text-muted">Front-end Developer</p>
                    </a>
                </div>
                <div class="col-6 animate-in-right col-lg-3">
                    <a href="#">
                        <img id="team" src="{% static 'images/lutfi.jpg' %}" class="center-block my-3 rounded-circle" width="300">
                        <h3 class="mb-0"><b>Muhammad Lutfi Arif</b></h3>
                        <p class="text-muted">Back-end Developer</p>
                    </a>
                </div>
                <div class="animate-in-left col-4 col-lg-3" style="">
                    <a href="#">
                        <img id="team" src="{% static 'images/fandy.jpg' %}" class="center-block my-3 rounded-circle" width="300">
                        <h3 class="mb-0"><b>Nur Rifandy</b></h3>
                        <p class="text-muted">Back-end developer</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Call to action -->
    <div class="py-5 section-aquamarine" id="register">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-md-left text-center">
                    <h1 class="text-white">Testimonies</h1>
                    <p>Pre-register to get a priority access to the event. Fares will be published later on.&nbsp; <br>Get the maximum from the lectures together with the possibility of joining exclusive side-events.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
</body>

{% endblock content %}

main/templates/register_for_admin.html
{% load static %}

{% block title %}
Register
{% endblock title %}

{% block css %}
<!-- CSS dependencies -->
{% endblock css %}
<header>
  <title>Toys Rent - Register Admin</title>
</header>

{% block content %}
<body class="h-100 w-100">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home&nbsp;</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="#">About</a> <a class="dropdown-item" href="#">Gallery</a> <a class="dropdown-item" href="#" contenteditable="true">Team</a> </div>
          </li>
        </ul>
        <a class="btn navbar-btn mx-2 text-white btn-outline-light" data-toggle="modal" data-target="#exampleModalCenter">Register now</a><a class="btn navbar-btn mx-2 text-white btn-outline-light" data-toggle="modal" data-target="#loginPopUp">Login</a>
      </div>
    </div>
  </nav>

  <!-- Action From-->
  <!-- Modal Login-->
  <div class="modal fade" id="loginPopUp" tabindex="-1" role="dialog" aria-labelledby="loginPopUp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header d-flex justify-content-center">
          <h3 class="modal-title">Login</h3>
        </div>
        <div class="modal-body">
          <form id="regist" method="POST" action="{% url 'login:auth' %}">
          {% csrf_token %}
          {{login}}
          <div class="mt-3 d-flex justify-content-end">
          <button class="btn btn-primary">Sign In</button>
        </div>
      </form>
        </div>
        <div class="modal-footer d-flex justify-content-start">
          <div>Don't you have an account? <a href="#">Sign Up</a></div>
        </div>
      </div>
    </div>
  </div>


  <!-- Modal Register-->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header d-flex justify-content-center">
          <h3 class="modal-title">Pick the Role</h3>
        </div>
        <div class="modal-body text-center d-flex justify-content-center">
          <div class="btn-group-vertical">
            <div>
              <form class="mb-2 mt-2" action="{% url 'main:admin' %}">
                <button class="btn btn-primary">Admin</button>
              </form>
              <form>
                <button class="btn btn-primary" formaction="{% url 'main:anggota' %}">Anggota</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Content -->
  <div class="container h-100 pt-4 pb-5 mb-3">
    <div class="h1 text-center p-3">REGISTER</div>
    <div class="row align-items-center h-100">
      <div class="col-lg-4"></div>
      <div class="col-lg-4 mx-aouto border p-3 mb-5" style="border-radius: 12px;">
        <form id="regist" method="POST" action="{% url 'main:register_admin' %}">
          {% csrf_token %}
          {{regis.as_p}}
            <div class="mt-3 d-flex justify-content-end">
            <button class="btn btn-primary">Sign Up</button>
          </div>
        </form>
      </div>
      <div class="col-lg-4"></div>
    </div>
  </div>
</body>

<link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

<link href="{% static 'css/base.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/header.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/footer.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/aquamarine.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/landing.css' %}" rel="stylesheet" type="text/css">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock content %}

main/templates/register_for_anggota.html
{% load static %}

{% block title %}

{% endblock title %}

{% block css %}

{% endblock css %}

{% block content %}
<header>
  <title>Toys Rent - Register Anggota</title>
</header>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home&nbsp;</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a class="dropdown-item" href="#">About</a> <a class="dropdown-item" href="#">Gallery</a> <a class="dropdown-item" href="#" contenteditable="true">Team</a> </div>
          </li>
        </ul>
        <a class="btn navbar-btn mx-2 text-white btn-outline-light" data-toggle="modal" data-target="#exampleModalCenter">Register now</a><a class="btn navbar-btn mx-2 text-white btn-outline-light" data-toggle="modal" data-target="#loginPopUp">Login</a>
      </div>
    </div>
  </nav>

  <!-- Action From-->
  <!-- Modal Login-->
  <div class="modal fade" id="loginPopUp" tabindex="-1" role="dialog" aria-labelledby="loginPopUp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header d-flex justify-content-center">
          <h3 class="modal-title">Login</h3>
        </div>
        <div class="modal-body">
          <form id="regist" method="POST" action="{% url 'login:auth' %}">
            {% csrf_token %}
            {{login}}
            <div class="mt-3 d-flex justify-content-end">
              <button class="btn btn-primary">Sign In</button>
            </div>
          </form>
        </div>
        <div class="modal-footer d-flex justify-content-start">
          <div>Don't you have an account? <a href="#">Sign Up</a></div>
        </div>
      </div>
    </div>
  </div>


  <!-- Modal Register-->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header d-flex justify-content-center">
          <h3 class="modal-title">Pick the Role</h3>
        </div>
        <div class="modal-body text-center d-flex justify-content-center">
          <div class="btn-group-vertical">
            <div>
              <form class="mb-2 mt-2" action="{% url 'main:admin' %}">
                <button class="btn btn-primary">Admin</button>
              </form>
              <form>
                <button class="btn btn-primary" formaction="{% url 'main:anggota' %}">Anggota</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Content -->
	<div class="container pt-5 pb-5 mb-5">
    <div class="h1 text-center p-3">REGISTER</div>
		<div class="row align-items-center h-100">
			<div class="col-lg-4"></div>
			<div class="col-lg-4 mx-auto border p-3 mb-5" style="border-radius: 12px;">
				<form id="regist" method="POST" action="{% url 'main:register_anggota' %}">
    			{% csrf_token %}
    			{{regis.as_p}}
    				<div class="mt-3 d-flex justify-content-end">
						<button class="btn btn-primary">Sign Up</button>
					</div>
				</form>
			</div>
			<div class="col-lg-4"></div>
		</div>
	</div>


<link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

<link href="{% static 'css/base.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/header.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/footer.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'css/aquamarine.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/landing.css' %}" rel="stylesheet" type="text/css">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</body>
{% endblock content %}